
function FlagObject(code, name, link){
		this.code = code;
		this.name = name;
		this.link = link;
	}

var countryFlagArray = [];

countryFlagArray.push(new FlagObject("AL", "Albania", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Flag_of_Albania.svg/100px-Flag_of_Albania.svg.png"));
countryFlagArray.push(new FlagObject("DZ", "Algeria", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Algeria.svg/100px-Flag_of_Algeria.svg.png"));
countryFlagArray.push(new FlagObject("AO", "Angola", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Angola.svg/100px-Flag_of_Angola.svg.png"));
countryFlagArray.push(new FlagObject("AG", "Antigua and Barbuda", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Antigua_and_Barbuda.svg/100px-Flag_of_Antigua_and_Barbuda.svg.png"));
countryFlagArray.push(new FlagObject("AR", "Argentina", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/100px-Flag_of_Argentina.svg.png"));
countryFlagArray.push(new FlagObject("AM", "Armenia", "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Flag_of_Armenia.svg/100px-Flag_of_Armenia.svg.png"));
countryFlagArray.push(new FlagObject("AW", "Aruba", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Aruba.svg/100px-Flag_of_Aruba.svg.png"));
countryFlagArray.push(new FlagObject("AU", "Australia", "https://upload.wikimedia.org/wikipedia/en/thumb/b/b9/Flag_of_Australia.svg/100px-Flag_of_Australia.svg.png"));
countryFlagArray.push(new FlagObject("AT", "Austria", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Austria.svg/100px-Flag_of_Austria.svg.png"));
countryFlagArray.push(new FlagObject("AZ", "Azerbaijan", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/100px-Flag_of_Azerbaijan.svg.png"));
countryFlagArray.push(new FlagObject("BS", "Bahamas", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Flag_of_the_Bahamas.svg/100px-Flag_of_the_Bahamas.svg.png"));
countryFlagArray.push(new FlagObject("BH", "Bahrain", "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Bahrain.svg/100px-Flag_of_Bahrain.svg.png"));
countryFlagArray.push(new FlagObject("BB", "Barbados", "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Flag_of_Barbados.svg/100px-Flag_of_Barbados.svg.png"));
countryFlagArray.push(new FlagObject("BY", "Belarus", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Flag_of_Belarus.svg/100px-Flag_of_Belarus.svg.png"));
countryFlagArray.push(new FlagObject("BE", "Belgium", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Belgium_%28civil%29.svg/100px-Flag_of_Belgium_%28civil%29.svg.png"));
countryFlagArray.push(new FlagObject("BJ", "Benin", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Benin.svg/100px-Flag_of_Benin.svg.png"));
countryFlagArray.push(new FlagObject("BM", "Bermuda", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bermuda.svg/100px-Flag_of_Bermuda.svg.png"));
countryFlagArray.push(new FlagObject("BO", "Bolivia", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Flag_of_Bolivia_%28state%29.svg/100px-Flag_of_Bolivia_%28state%29.svg.png"));
countryFlagArray.push(new FlagObject("BA", "Bosnia and Herzegovina", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bosnia_and_Herzegovina.svg/100px-Flag_of_Bosnia_and_Herzegovina.svg.png"));
countryFlagArray.push(new FlagObject("BW", "Botswana", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_Botswana.svg/100px-Flag_of_Botswana.svg.png"));
countryFlagArray.push(new FlagObject("BR", "Brazil", "https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/100px-Flag_of_Brazil.svg.png"));
countryFlagArray.push(new FlagObject("VG", "British Virgin Islands", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Flag_of_the_British_Virgin_Islands.svg/100px-Flag_of_the_British_Virgin_Islands.svg.png"));
countryFlagArray.push(new FlagObject("BG", "Bulgaria", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/100px-Flag_of_Bulgaria.svg.png"));
countryFlagArray.push(new FlagObject("BI", "Burundi", "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_Burundi.svg/100px-Flag_of_Burundi.svg.png"));
countryFlagArray.push(new FlagObject("CM", "Cameroon", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Cameroon.svg/100px-Flag_of_Cameroon.svg.png"));
countryFlagArray.push(new FlagObject("CA", "Canada", "https://upload.wikimedia.org/wikipedia/en/thumb/c/cf/Flag_of_Canada.svg/100px-Flag_of_Canada.svg.png"));
countryFlagArray.push(new FlagObject("CV", "Cape Verde", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Cape_Verde.svg/100px-Flag_of_Cape_Verde.svg.png"));
countryFlagArray.push(new FlagObject("KY", "Cayman Islands", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_the_Cayman_Islands.svg/100px-Flag_of_the_Cayman_Islands.svg.png"));
countryFlagArray.push(new FlagObject("CL", "Chile", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Flag_of_Chile.svg/100px-Flag_of_Chile.svg.png"));
countryFlagArray.push(new FlagObject("CN", "China", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/100px-Flag_of_the_People%27s_Republic_of_China.svg.png"));
countryFlagArray.push(new FlagObject("CO", "Colombia", "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/100px-Flag_of_Colombia.svg.png"));
countryFlagArray.push(new FlagObject("CD", "Congo", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_the_Republic_of_the_Congo.svg/100px-Flag_of_the_Republic_of_the_Congo.svg.png"));
countryFlagArray.push(new FlagObject("CD", "DR Congo", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg/100px-Flag_of_the_Democratic_Republic_of_the_Congo.svg.png"));
countryFlagArray.push(new FlagObject("CK", "Cook Islands", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Flag_of_the_Cook_Islands.svg/100px-Flag_of_the_Cook_Islands.svg.png"));
countryFlagArray.push(new FlagObject("CR", "Costa Rica", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Costa_Rica_%28state%29.svg/100px-Flag_of_Costa_Rica_%28state%29.svg.png"));
countryFlagArray.push(new FlagObject("HR", "Croatia", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/100px-Flag_of_Croatia.svg.png"));
countryFlagArray.push(new FlagObject("CU", "Cuba", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Flag_of_Cuba.svg/100px-Flag_of_Cuba.svg.png"));
countryFlagArray.push(new FlagObject("CY", "Cyprus", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Cyprus.svg/100px-Flag_of_Cyprus.svg.png"));
countryFlagArray.push(new FlagObject("CZ", "Czech Republic", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_Czech_Republic.svg/100px-Flag_of_the_Czech_Republic.svg.png"));
countryFlagArray.push(new FlagObject("DK", "Denmark", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/100px-Flag_of_Denmark.svg.png"));
countryFlagArray.push(new FlagObject("DJ", "Djibouti", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_Djibouti.svg/100px-Flag_of_Djibouti.svg.png"));
countryFlagArray.push(new FlagObject("DM", "Dominica", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Flag_of_Dominica.svg/100px-Flag_of_Dominica.svg.png"));
countryFlagArray.push(new FlagObject("DO", "Dominican Republic", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_the_Dominican_Republic.svg/100px-Flag_of_the_Dominican_Republic.svg.png"));
countryFlagArray.push(new FlagObject("EC", "Ecuador", "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/100px-Flag_of_Ecuador.svg.png"));
countryFlagArray.push(new FlagObject("EG", "Egypt", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/100px-Flag_of_Egypt.svg.png"));
countryFlagArray.push(new FlagObject("SV", "El Salvador", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_El_Salvador.svg/100px-Flag_of_El_Salvador.svg.png"));
countryFlagArray.push(new FlagObject("ER", "Eritrea", "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Flag_of_Eritrea.svg/100px-Flag_of_Eritrea.svg.png"));
countryFlagArray.push(new FlagObject("EE", "Estonia", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Flag_of_Estonia.svg/100px-Flag_of_Estonia.svg.png"));
countryFlagArray.push(new FlagObject("ET", "Ethiopia", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Flag_of_Ethiopia.svg/100px-Flag_of_Ethiopia.svg.png"));
countryFlagArray.push(new FlagObject("FJ", "Fiji", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Fiji.svg/100px-Flag_of_Fiji.svg.png"));
countryFlagArray.push(new FlagObject("FI", "Finland", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Finland.svg/100px-Flag_of_Finland.svg.png"));
countryFlagArray.push(new FlagObject("FR", "France", "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/100px-Flag_of_France.svg.png"));
countryFlagArray.push(new FlagObject("GA", "Gabon", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Flag_of_Gabon.svg/100px-Flag_of_Gabon.svg.png"));
countryFlagArray.push(new FlagObject("GE", "Georgia", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Georgia.svg/100px-Flag_of_Georgia.svg.png"));
countryFlagArray.push(new FlagObject("DE", "Germany", "https://upload.wikimedia.org/wikipedia/en/thumb/b/ba/Flag_of_Germany.svg/100px-Flag_of_Germany.svg.png"));
countryFlagArray.push(new FlagObject("GH", "Ghana", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Ghana.svg/100px-Flag_of_Ghana.svg.png"));
countryFlagArray.push(new FlagObject("GB", "Great Britain", "https://upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/100px-Flag_of_the_United_Kingdom.svg.png"));
countryFlagArray.push(new FlagObject("GR", "Greece", "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Greece.svg/100px-Flag_of_Greece.svg.png"));
countryFlagArray.push(new FlagObject("GL", "Greenland", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_Greenland.svg/100px-Flag_of_Greenland.svg.png"));
countryFlagArray.push(new FlagObject("GD", "Grenada", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Grenada.svg/100px-Flag_of_Grenada.svg.png"));
countryFlagArray.push(new FlagObject("GT", "Guatemala", "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Flag_of_Guatemala.svg/100px-Flag_of_Guatemala.svg.png"));
countryFlagArray.push(new FlagObject("GW", "Guinea-Bissau", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Guinea-Bissau.svg/100px-Flag_of_Guinea-Bissau.svg.png"));
countryFlagArray.push(new FlagObject("GY", "Guyana", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_Guyana.svg/100px-Flag_of_Guyana.svg.png"));
countryFlagArray.push(new FlagObject("HN", "Honduras", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Flag_of_Honduras.svg/100px-Flag_of_Honduras.svg.png"));
countryFlagArray.push(new FlagObject("HK", "Hong Kong", "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Flag_of_Hong_Kong.svg/100px-Flag_of_Hong_Kong.svg.png"));
countryFlagArray.push(new FlagObject("HU", "Hungary", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Flag_of_Hungary.svg/100px-Flag_of_Hungary.svg.png"));
countryFlagArray.push(new FlagObject("IS", "Iceland", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Iceland.svg/100px-Flag_of_Iceland.svg.png"));
countryFlagArray.push(new FlagObject("IN", "India", "https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/100px-Flag_of_India.svg.png"));
countryFlagArray.push(new FlagObject("ID", "Indonesia", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/100px-Flag_of_Indonesia.svg.png"));
countryFlagArray.push(new FlagObject("IR", "Iran", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/100px-Flag_of_Iran.svg.png"));
countryFlagArray.push(new FlagObject("IQ", "Iraq", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Iraq.svg/100px-Flag_of_Iraq.svg.png"));
countryFlagArray.push(new FlagObject("IE", "Ireland", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Flag_of_Ireland.svg/100px-Flag_of_Ireland.svg.png"));
countryFlagArray.push(new FlagObject("IL", "Israel", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Israel.svg/100px-Flag_of_Israel.svg.png"));
countryFlagArray.push(new FlagObject("IT", "Italy", "https://upload.wikimedia.org/wikipedia/en/thumb/0/03/Flag_of_Italy.svg/100px-Flag_of_Italy.svg.png"));
countryFlagArray.push(new FlagObject("CI", "Ivory Coast", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_C%C3%B4te_d%27Ivoire.svg/100px-Flag_of_C%C3%B4te_d%27Ivoire.svg.png"));
countryFlagArray.push(new FlagObject("JM", "Jamaica", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Jamaica.svg/100px-Flag_of_Jamaica.svg.png"));
countryFlagArray.push(new FlagObject("JP", "Japan", "https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/100px-Flag_of_Japan.svg.png"));
countryFlagArray.push(new FlagObject("JO", "Jordan", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Flag_of_Jordan.svg/100px-Flag_of_Jordan.svg.png"));
countryFlagArray.push(new FlagObject("KZ", "Kazakhstan", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kazakhstan.svg/100px-Flag_of_Kazakhstan.svg.png"));
countryFlagArray.push(new FlagObject("KE", "Kenya", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Kenya.svg/100px-Flag_of_Kenya.svg.png"));
countryFlagArray.push(new FlagObject("KG", "Kyrgyzstan", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Flag_of_Kyrgyzstan.svg/100px-Flag_of_Kyrgyzstan.svg.png"));
countryFlagArray.push(new FlagObject("KG", "Kuwait", "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Olympic_flag.svg/100px-Olympic_flag.svg.png"));
countryFlagArray.push(new FlagObject("LV", "Latvia", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Latvia.svg/100px-Flag_of_Latvia.svg.png"));
countryFlagArray.push(new FlagObject("LB", "Lebanon", "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Flag_of_Lebanon.svg/100px-Flag_of_Lebanon.svg.png"));
countryFlagArray.push(new FlagObject("LS", "Lesotho", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Flag_of_Lesotho.svg/100px-Flag_of_Lesotho.svg.png"));
countryFlagArray.push(new FlagObject("LR", "Liberia", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Flag_of_Liberia.svg/100px-Flag_of_Liberia.svg.png"));
countryFlagArray.push(new FlagObject("LY", "Libya", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Libya.svg/100px-Flag_of_Libya.svg.png"));
countryFlagArray.push(new FlagObject("LT", "Lithuania", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Lithuania.svg/100px-Flag_of_Lithuania.svg.png"));
countryFlagArray.push(new FlagObject("LU", "Luxembourg", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Flag_of_Luxembourg.svg/100px-Flag_of_Luxembourg.svg.png"));
countryFlagArray.push(new FlagObject("MY", "Malaysia", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Flag_of_Malaysia.svg/100px-Flag_of_Malaysia.svg.png"));
countryFlagArray.push(new FlagObject("ML", "Mali", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Mali.svg/100px-Flag_of_Mali.svg.png"));
countryFlagArray.push(new FlagObject("MU", "Mauritius", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Mauritius.svg/100px-Flag_of_Mauritius.svg.png"));
countryFlagArray.push(new FlagObject("MX", "Mexico", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/100px-Flag_of_Mexico.svg.png"));
countryFlagArray.push(new FlagObject("MD", "Moldova", "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Moldova.svg/100px-Flag_of_Moldova.svg.png"));
countryFlagArray.push(new FlagObject("MN", "Mongolia", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Mongolia.svg/100px-Flag_of_Mongolia.svg.png"));
countryFlagArray.push(new FlagObject("ME", "Montenegro", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Flag_of_Montenegro.svg/100px-Flag_of_Montenegro.svg.png"));
countryFlagArray.push(new FlagObject("MA", "Morocco", "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/100px-Flag_of_Morocco.svg.png"));
countryFlagArray.push(new FlagObject("MZ", "Mozambique", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Mozambique.svg/100px-Flag_of_Mozambique.svg.png"));
countryFlagArray.push(new FlagObject("MM", "Myanmar", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Flag_of_Myanmar.svg/100px-Flag_of_Myanmar.svg.png"));
countryFlagArray.push(new FlagObject("NA", "Namibia", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Namibia.svg/100px-Flag_of_Namibia.svg.png"));
countryFlagArray.push(new FlagObject("NL", "Netherlands", "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/100px-Flag_of_the_Netherlands.svg.png"));
countryFlagArray.push(new FlagObject("NZ", "New Zealand", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Flag_of_New_Zealand.svg/100px-Flag_of_New_Zealand.svg.png"));
countryFlagArray.push(new FlagObject("NE", "Niger", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Flag_of_Niger.svg/100px-Flag_of_Niger.svg.png"));
countryFlagArray.push(new FlagObject("NG", "Nigeria", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Nigeria.svg/100px-Flag_of_Nigeria.svg.png"));
countryFlagArray.push(new FlagObject("KP", "North Korea", "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Flag_of_North_Korea.svg/100px-Flag_of_North_Korea.svg.png"));
countryFlagArray.push(new FlagObject("NO", "Norway", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/100px-Flag_of_Norway.svg.png"));
countryFlagArray.push(new FlagObject("OM", "Oman", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Oman.svg/100px-Flag_of_Oman.svg.png"));
countryFlagArray.push(new FlagObject("PS", "Palestine", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Palestine.svg/100px-Flag_of_Palestine.svg.png"));
countryFlagArray.push(new FlagObject("PA", "Panama", "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Flag_of_Panama.svg/100px-Flag_of_Panama.svg.png"));
countryFlagArray.push(new FlagObject("PG", "Papua New Guinea", "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Flag_of_Papua_New_Guinea.svg/100px-Flag_of_Papua_New_Guinea.svg.png"));
countryFlagArray.push(new FlagObject("PY", "Paraguay", "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Paraguay.svg/100px-Flag_of_Paraguay.svg.png"));
countryFlagArray.push(new FlagObject("PE", "Peru", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Flag_of_Peru.svg/100px-Flag_of_Peru.svg.png"));
countryFlagArray.push(new FlagObject("PH", "Philippines", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_the_Philippines.svg/100px-Flag_of_the_Philippines.svg.png"));
countryFlagArray.push(new FlagObject("PL", "Poland", "https://upload.wikimedia.org/wikipedia/en/thumb/1/12/Flag_of_Poland.svg/100px-Flag_of_Poland.svg.png"));
countryFlagArray.push(new FlagObject("PT", "Portugal", "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/100px-Flag_of_Portugal.svg.png"));
countryFlagArray.push(new FlagObject("PR", "Puerto Rico", "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Flag_of_Puerto_Rico.svg/100px-Flag_of_Puerto_Rico.svg.png"));
countryFlagArray.push(new FlagObject("QA", "Qatar", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Qatar.svg/100px-Flag_of_Qatar.svg.png"));
countryFlagArray.push(new FlagObject("  ", "Refugee Olympic Athletes at the 2016 Summer Ol", "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Olympic_flag.svg/100px-Olympic_flag.svg.png"));
countryFlagArray.push(new FlagObject("RO", "Romania", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/100px-Flag_of_Romania.svg.png"));
countryFlagArray.push(new FlagObject("RU", "Russia", "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/100px-Flag_of_Russia.svg.png"));
countryFlagArray.push(new FlagObject("RW", "Rwanda", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Rwanda.svg/100px-Flag_of_Rwanda.svg.png"));
countryFlagArray.push(new FlagObject("KN", "Saint Kitts and Nevis", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Saint_Kitts_and_Nevis.svg/100px-Flag_of_Saint_Kitts_and_Nevis.svg.png"));
countryFlagArray.push(new FlagObject("LC", "Saint Lucia", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Saint_Lucia.svg/100px-Flag_of_Saint_Lucia.svg.png"));
countryFlagArray.push(new FlagObject("VC", "Saint Vincent and the Grenadines", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Flag_of_Saint_Vincent_and_the_Grenadines.svg/100px-Flag_of_Saint_Vincent_and_the_Grenadines.svg.png"));
countryFlagArray.push(new FlagObject("WS", "Samoa", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Samoa.svg/100px-Flag_of_Samoa.svg.png"));
countryFlagArray.push(new FlagObject("SM", "San Marino", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Flag_of_San_Marino.svg/100px-Flag_of_San_Marino.svg.png"));
countryFlagArray.push(new FlagObject("SA", "Saudi Arabia", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/100px-Flag_of_Saudi_Arabia.svg.png"));
countryFlagArray.push(new FlagObject("SN", "Senegal", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Flag_of_Senegal.svg/100px-Flag_of_Senegal.svg.png"));
countryFlagArray.push(new FlagObject("RS", "Serbia", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Flag_of_Serbia.svg/100px-Flag_of_Serbia.svg.png"));
countryFlagArray.push(new FlagObject("SC", "Seychelles", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Seychelles.svg/100px-Flag_of_Seychelles.svg.png"));
countryFlagArray.push(new FlagObject("SG", "Singapore", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/100px-Flag_of_Singapore.svg.png"));
countryFlagArray.push(new FlagObject("SK", "Slovakia", "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Flag_of_Slovakia.svg/100px-Flag_of_Slovakia.svg.png"));
countryFlagArray.push(new FlagObject("SI", "Slovenia", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Flag_of_Slovenia.svg/100px-Flag_of_Slovenia.svg.png"));
countryFlagArray.push(new FlagObject("ZA", "South Africa", "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Flag_of_South_Africa.svg/100px-Flag_of_South_Africa.svg.png"));
countryFlagArray.push(new FlagObject("KR", "South Korea", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/100px-Flag_of_South_Korea.svg.png"));
countryFlagArray.push(new FlagObject("ES", "Spain", "https://upload.wikimedia.org/wikipedia/en/thumb/9/9a/Flag_of_Spain.svg/100px-Flag_of_Spain.svg.png"));
countryFlagArray.push(new FlagObject("LK", "Sri Lanka", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Sri_Lanka.svg/100px-Flag_of_Sri_Lanka.svg.png"));
countryFlagArray.push(new FlagObject("SD", "Sudan", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Sudan.svg/100px-Flag_of_Sudan.svg.png"));
countryFlagArray.push(new FlagObject("SE", "Sweden", "https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Flag_of_Sweden.svg/100px-Flag_of_Sweden.svg.png"));
countryFlagArray.push(new FlagObject("CH", "Switzerland", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Switzerland.svg/20px-Flag_of_Switzerland.svg.png"));
countryFlagArray.push(new FlagObject("CH", "Syria", "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Flag_of_Syria.svg/100px-Flag_of_Syria.svg.png"));
countryFlagArray.push(new FlagObject("  ", "Chinese Taipei", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Flag_of_Chinese_Taipei_for_Olympic_games.svg/100px-Flag_of_Chinese_Taipei_for_Olympic_games.svg.png"));
countryFlagArray.push(new FlagObject("TJ", "Tajikistan", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Tajikistan.svg/100px-Flag_of_Tajikistan.svg.png"));
countryFlagArray.push(new FlagObject("TZ", "Tanzania", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tanzania.svg/100px-Flag_of_Tanzania.svg.png"));
countryFlagArray.push(new FlagObject("TH", "Thailand", "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/100px-Flag_of_Thailand.svg.png"));
countryFlagArray.push(new FlagObject("TT", "Trinidad and Tobago", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Flag_of_Trinidad_and_Tobago.svg/100px-Flag_of_Trinidad_and_Tobago.svg.png"));
countryFlagArray.push(new FlagObject("TO", "Tonga", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Tonga.svg/100px-Flag_of_Tonga.svg.png"));
countryFlagArray.push(new FlagObject("TN", "Tunisia", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Tunisia.svg/100px-Flag_of_Tunisia.svg.png"));
countryFlagArray.push(new FlagObject("TR", "Turkey", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/100px-Flag_of_Turkey.svg.png"));
countryFlagArray.push(new FlagObject("UG", "Uganda", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Flag_of_Uganda.svg/100px-Flag_of_Uganda.svg.png"));
countryFlagArray.push(new FlagObject("UA", "Ukraine", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Ukraine.svg/100px-Flag_of_Ukraine.svg.png"));
countryFlagArray.push(new FlagObject("AE", "United Arab Emirates", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_United_Arab_Emirates.svg/100px-Flag_of_the_United_Arab_Emirates.svg.png"));
countryFlagArray.push(new FlagObject("US", "United States", "https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/100px-Flag_of_the_United_States.svg.png"));
countryFlagArray.push(new FlagObject("UY", "Uruguay", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/100px-Flag_of_Uruguay.svg.png"));
countryFlagArray.push(new FlagObject("UZ", "Uzbekistan", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Uzbekistan.svg/100px-Flag_of_Uzbekistan.svg.png"));
countryFlagArray.push(new FlagObject("VE", "Venezuela", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Venezuela.svg/100px-Flag_of_Venezuela.svg.png"));
countryFlagArray.push(new FlagObject("VN", "Vietnam", "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Vietnam.svg/100px-Flag_of_Vietnam.svg.png"));
countryFlagArray.push(new FlagObject("VI", "Virgin Islands", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Flag_of_the_United_States_Virgin_Islands.svg/100px-Flag_of_the_United_States_Virgin_Islands.svg.png"));
countryFlagArray.push(new FlagObject("ZM", "Zambia", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Zambia.svg/100px-Flag_of_Zambia.svg.png"));
countryFlagArray.push(new FlagObject("ZW", "Zimbabwe", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Flag_of_Zimbabwe.svg/100px-Flag_of_Zimbabwe.svg.png"));

var countryFlag = {};
for (var i = 0; i < countryFlagArray.length; i++) {
	var flag = countryFlagArray[i];
	countryFlag[flag.code] = flag;
}